version: "{build}"
image: Visual Studio 2019
clone_folder: c:\GOPATH\src\github.com\errata-ai\vale
environment:
  GOPATH: c:\GOPATH
  GOROOT: C:\go
  GOVERSION: 1.20.3
init:
  - cmd: set PATH=C:\MinGW\bin;%cd%/bin;%PATH%
  - cmd: copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\Ruby24\bin;%cd%;%PATH%

  - rmdir C:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env

  - cinst ansicon

  - pip install sphinx
  - gem install asciidoctor

  - choco install xsltproc
  # Git on AppVeyor includes a non-functional xsltproc. Remove this.
  - if exist "%ProgramFiles%\Git\usr\bin\xsltproc.exe" del "%ProgramFiles%\Git\usr\bin\xsltproc.exe"

  - curl -fsSL -o C:\dita-ot-3.4.zip https://github.com/dita-ot/dita-ot/releases/download/3.4/dita-ot-3.4.zip
  - 7z x C:\dita-ot-3.4.zip -y -r -oC:\dita
  - set PATH=C:\dita\dita-ot-3.4\bin;%PATH%
build_script:
  - cmd: go version
  - cmd: make setup
  - cmd: make build os=windows exe=vale.exe
test_script:
  - cmd: make test
# after_test:
#   - cmd: make compare
