// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWithVale(arg1) {
  return window['go']['main']['App']['CheckWithVale'](arg1);
}

export function CheckWithValeTemp(arg1) {
  return window['go']['main']['App']['CheckWithValeTemp'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function TestVale(arg1) {
  return window['go']['main']['App']['TestVale'](arg1);
}
