// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWithVale(arg1:string,arg2:string):Promise<string>;

export function CheckWithValeTemp(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function TestVale(arg1:string):Promise<string>;
